# Generated by Django 5.0.6 on 2024-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_profile_user_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='institute'),
        ),
    ]
