# Generated by Django 5.0.6 on 2024-06-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithm', '0002_alter_algorithm_category_alter_algorithm_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='algorithmcategory',
            table='algorithm_categories',
        ),
    ]
