# Generated by Django 5.0.6 on 2024-06-21 10:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithm', '0003_alter_algorithmcategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='algorithmcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
